### ISSUE TITLE
Review of the location of /core folder to allow for better collaboration (suggestion)

### ISSUE THREAD

**Issue by damms005** [pagecarton/pagecarton#1]
From the way the code is currently structured, I believe we can still better optimize for collaboration.

I believe we can achieve this new, better, pro-collaboration PageCarton by making the installation "core-folder-agnostic", i.e. the `/core` folder existing anywhere in the filesystem as long as the web server has requisite file permissions.
For example, since installation is simply a dump of the `local_html` folder, collaborators should be able to run their normal PageCarton via `local_html` upon cloning the repo, without running into any issues.
This may require us specifying the `/core` folder via some config file (which means normal default installation would have specified regular users' appropriate `/core` folder location); or even inside the controller `index.php`

In this way, collaborators can simply clone the repo, make `local_html` available to webserver's `document_root` folder and then simply starts developing PageCarton. I believe this seems like a more direct way to contribute to PageCarton.

With the status quo, if a developer wants to contribute to code inside `local_html` and thus installs PC via the currently prescribed process, it is not simply a straight-forward process to make such contribution because the "functioning" contents of the target folder (`local_html`) are now elsewhere.

I want to believe that this will give PageCarton a more natural flow (for collaborators) and make the process and the whole structure feel much more open and dynamic - easy to tweak.

**Comment by ayoolafalola** [comment]
Great submission @damms005. Currently, location of the core is hard-coded in the `index.php` controller. My suggested fix is to have it look up from an arbitrary JSON configuration file seated in the `local_html` directory.

**Comment by damms005** [comment]
@ayoolafalola thanks for the expedient fix! @ 8f5c03c0
