### ISSUE TITLE
The new pagecarton-1.8.68 version has a problem with themes.

### ISSUE THREAD

**Issue by aukc1970** [pagecarton/pagecarton#10]
The new pagecarton-1.8.68 version has a problem with themes.
When you click to edit the topic, nothing happens. It is not possible to edit the topic. And it is impossible to create a theme from the HTML template. Check please edit themes and create themes from html template in the new version.

**Comment by ayoolafalola** [comment]
Please check the latest version 1.8.69

**Comment by aukc1970** [comment]
Thanks theme editing now works!
Please check the creation of a theme from the HTML template.

**Comment by aukc1970** [comment]
Please check the creation of a theme from an HTML template. Pagecarton-1.8.69 problems with automatic detection of navigation and editable sections.

**Comment by ayoolafalola** [comment]
This should be fixed now. Can you reinstall 1.8.69

**Comment by aukc1970** [comment]
Thank ! Everything is great !

**Comment by ayoolafalola** [comment]
Awesome! Thanks for the feedback.
