### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by softmayor** [pagecarton/pagecarton#11]
## Sign-In / Sign-out button is required from the Admin panel.
Please take note let there be sign-in/sign-out button from the next PageCarton version.

## Time out error
(localhost is currently unable to handle this request.) this error occur while running on local server can this be fixed from the nest update

## Theme upload after sign up
Can PageCarton allow its user to upload theme from their computer during Website Wizard tour please let this feature be applied to both online and offline.

## PHP extension
what can PC do to solve this error message /cgi-sys/pc_installer.php?stage=start though it a minor issue but i believe something can be done if it was carefully look into..

## Thank you.

**Comment by damms005** [comment]
Closed for lack of clarity. Kindly open another separate issue for each of the issues you raised, and please do so under the appropriate issue page
