### ISSUE TITLE
Maintenance mode HTML

### ISSUE THREAD

**Issue by geektutor** [pagecarton/pagecarton#3]
I will like to add a maintenance.html to core so that when maintenance/upgrade is going on, it can be shown to the end user that the site is under maintenance. 

What directory do I add this?

**Comment by ayoolafalola** [comment]
Create your directory in `/pagecarton/core/application/documents/layout`

**Comment by Isaacdaramola** [comment]
> I will like to add a maintenance.html to core so that when maintenance/upgrade is going on, it can be shown to the end user that the site is under maintenance.
> 
> What directory do I add this?



> Create your directory in `/pagecarton/core/application/documents/layout`

I think an editable content would do better. 
Which means, that the admin should be able to edit the content for his/her preferred statement.

**Comment by damms005** [comment]
@geektutor please check the comment by @ayoolafalola in order to make the contribution you suggested regarding the maintenance page. Kindly open another issue if you seek more clarifications
