### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by Product-Wizard** [pagecarton/pagecarton#37]
When a particular device (PC) does not meet the requirement for the installation, they should be referred to a blog post "On _how to install the missing library_" .
e.g  GD Library is missing on your device, ' see how you can install it '.
![Installation Guide Enhancment](https://github.com/pagecarton/pagecarton/assets/159847551/0c8beacd-b919-4715-8651-e8d15f1eb1e2)

**Comment by damms005** [comment]
I'm not sure how that should work because I don't think hard-coding links to blog posts will scale with respect to time and space.

I think this is a Google/Chat GPT thing though.

**Comment by Product-Wizard** [comment]
Okay, how about? As a user attempting to install Page Carton on my device,
I want to be informed if any required libraries are missing,
So that I can quickly resolve the issue and proceed with the installation.
