### ISSUE TITLE
Tell me what files need to be translated to make the interface in Russian ?

### ISSUE THREAD

**Issue by aukc1970** [pagecarton/pagecarton#4]
Good day! Tell me what files need to be translated to make the interface in Russian ?

**Comment by ayoolafalola** [comment]
That would be awesome. Can you please join the community on http://www.pagecarton.org/join 
That way, will show you how you can be of help translating this to Russian. 
Thank you so much for your help.
Regards
    On Wednesday, May 15, 2019, 8:24:30 AM GMT+1, aukc1970 <notifications@github.com> wrote:  
 
 
Good day! Tell me what files need to be translated to make the interface in Russian ?

**Comment by aukc1970** [comment]
Thank you ! Good ! I registered on Your forum.
