### ISSUE TITLE
[Feature request] It would be good if the CMS interface was in different languages, then more people could use it !

### ISSUE THREAD

**Issue by aukc1970** [pagecarton/pagecarton#5]
Good day! I like Your CMS ! It would be good if the CMS interface was in different languages, then more people could use it ! Many CMS use for different languages i18n Here is the site: https://www.i18next.com

**Comment by aukc1970** [comment]
Here's another example: 
https://github.com/olivierperez/o80-i18n

**Comment by aukc1970** [comment]
https://github.com/i18next/i18next

**Comment by ayoolafalola** [comment]
Sure. Thanks for the suggestion. We actually have a pending translation project for PageCarton that was mostly abandoned. We can restart the project and add it to the coming PageCarton 1.9. We already have some internal translation classes and API that can be used. 

Those APIs can be made to import directly from o80-i18n that you suggested.

**Comment by aukc1970** [comment]
The ability to translate the backend admin panelinto other languages. It is even better that the translation was automatic via Google or another translator. The ability to add and change the translation manually.
