### ISSUE TITLE
For accelerated development of html templates.

### ISSUE THREAD

**Issue by aukc1970** [pagecarton/pagecarton#7]
For accelerated development of html templates.
There is a wonderful program called Nicepage ! Here are the links to the site:
https://github.com/NicepageApp/Nicepage
https://nicepage.com/
https://nicepage.com/doc/article/20348/web-design-3-0-when-your-web-design-really-matters
Just do not know whether or not the license allows you to make HTML-based templates for CMS ? Although for Wordpress or Joomla program can generate templates.

**Comment by ayoolafalola** [comment]
Checking this out. Looks quite interesting. 

Meanwhile, we have been using ready-made templates from several sources documented here http://docs.pagecarton.org/2018/10/10/where-to-get-free-html-templates-to-build-pagecarton-themes.html

**Comment by aukc1970** [comment]
I tried with another template. The page creates well without errors. But in the code text is encoded. Here are the screenshots.
https://drive.google.com/open?id=1DSS6k884uG9PPEhTfSE5OhxrIeSQ6BXH
https://drive.google.com/open?id=1f0hK-txzxhc_Ggp5kjcygj47_hfyw9MZ
https://drive.google.com/open?id=17he-FN8jpzz1GE9bQUQVAICFTLaY-ypn

**Comment by aukc1970** [comment]
From yours I liked these:
https://colorlib.com/wp/templates/
But in order to remove the copyright they ask for $ 21 for one template or $ 99 for all free templates.
https://colorlib.com/wp/licence/

**Comment by ayoolafalola** [comment]
Thanks for all wonderful comments and contributions @aukc1970
