### ISSUE TITLE
For local development, there are wonderful local servers.

### ISSUE THREAD

**Issue by aukc1970** [pagecarton/pagecarton#8]
For local development, there are wonderful local servers.
Cross platform For Mac:
https://ampps.com/download
https://ampps.com/
https://ampps.com/apps
For Windows:
https://laragon.org/
https://laragon.org/download/
https://github.com/leokhoa/laragon
https://ospanel.io/
https://www.easyphp.org/download.php

**Comment by ayoolafalola** [comment]
Awesome contribution here @aukc1970

**Comment by ladaposamuel** [comment]
This is not supposed to be an `issue` IMO

**Comment by ayoolafalola** [comment]
@ladaposamuel, you are right.
